Workflow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -88,6 +88,9 @@ jobs:
             echo "✅ Tests PASSED!"
           fi
 
+          echo "🔹 Checking AWS Credentials..."
+          aws sts get-caller-identity || (echo "AWS Credentials Invalid!" && exit 1)
+
           aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws configure set aws_session_token ${{ secrets.AWS_SESSION_TOKEN }}
@@ -97,17 +100,21 @@ jobs:
           aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${AWS_ECR_BACKEND}
           aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${AWS_ECR_FRONTEND}
 
+          echo "🔹 Checking if AWS_ECR_BACKEND and AWS_ECR_FRONTEND are set..."
+          echo "AWS_ECR_BACKEND=${AWS_ECR_BACKEND}"
+          echo "AWS_ECR_FRONTEND=${AWS_ECR_FRONTEND}"
+
           echo "Building and pushing backend Docker image..."
           cd /home/ec2-user/hottake/backend
           docker build -t hot-take-image .
-          docker tag hot-take-image:latest ${AWS_ECR_BACKEND}:latest
-          docker push ${AWS_ECR_BACKEND}:latest
+          docker tag hot-take-image:latest ${AWS_ECR_BACKEND}/hot-take-backend:latest
+          docker push ${AWS_ECR_BACKEND}/hot-take-backend:latest
 
           echo "Building and pushing frontend Docker image..."
           cd /home/ec2-user/hottake/frontend
           docker build -t hot-take-image-frontend .
-          docker tag hot-take-image-frontend:latest ${AWS_ECR_FRONTEND}:latest
-          docker push ${AWS_ECR_FRONTEND}:latest
+          docker tag hot-take-image-frontend:latest ${AWS_ECR_FRONTEND}/hot-take-frontend:latest
+          docker push ${AWS_ECR_FRONTEND}/hot-take-frontend:latest
 
           exit $EXIT_CODE
           EOF
